export type RootStackParamList = {
    Introduction: undefined;
    Login: undefined;
    Register: { role: string };
    Home: undefined;
    Products: { search?: string };
    ProductDetail: { product: any };
    Cart: undefined;
    Checkout: { subtotal: number };
    Transactions: undefined;
    Notifications: undefined;
    Profile: undefined;
    ConversationList: undefined;
    Chat: { conversationId: string; receiverName: string; receiverId?: number };
    ShipperDashboard: undefined;
    OrderDetail: { orderId: number };
    CreateBanner: undefined;
    AdminBanners: undefined;
    ManageBanners: undefined;
    ShopProfile: { shopId: number };
};
